#page title
page_title                                : 2US                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6450370428                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id6450370428                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_launcher_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "2US: Couples & Relationship"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Experience deeper connection, enhance your relationship

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : "at:"
your_link                                 :
your_city                                 :
email_address                             : 2usrelationshipapp@gmail.com
facebook_username                         : 2US-Couples-Relationship-103071712883852
instagram_username                        : 2usapp
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Recommendations
    description                           : Experience daily and weekly tasks that keep your relationship on track and provide opportunities for growth and communication.
    fontawesome_icon_name                 : lightbulb
    
  - title                                 : Challenges
    description                           : Engage in fun and meaningful challenges together designed to strengthen your emotional connection and create lasting memories.
    fontawesome_icon_name                 : trophy

  - title                                 : Interactive Games
    description                           : Enjoy interactive games specially crafted for couples, providing moments of joy and intimacy.
    fontawesome_icon_name                 : star

  - title                                 : AI-Powered Gift Ideas
    description                           : Get inspired with thoughtful gift ideas, generated by cutting-edge AI technology, to surprise your loved ones and show them how much you care.
    fontawesome_icon_name                 : magic

  - title                                 : Custom Tasks
    description                           : Personalize tasks based on your preferences, ensuring they align with your unique relationship journey.
    fontawesome_icon_name                 : circlecheck
  
  - title                                 : Notes
    description                           : Whether it's a gift idea, travel itinerary, or simply your thoughts, notes provide a convenient space to keep everything organized and at your fingertips.
    fontawesome_icon_name                 : list

  - title                                 : # Smart App Banner
    description                           : # Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : # arrow-alt-circle-down

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/cover_image_3.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#696868"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
